# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIjr1nTIzwITerk6oko5-LusqVYfJBoJ
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

try:
    df = pd.read_csv('/content/weather_cleaned_phase1.csv')
    print("Phase 1 dataset loaded successfully!")
except FileNotFoundError:
    print("Error: Phase 1 file not found.")

# Convert time (optional)
df['time'] = pd.to_datetime(df['time'])
df['hour'] = df['time'].dt.hour

# Create target
df['target_temperature'] = df['temperature_2m_mean'].shift(-1)
df = df.dropna()

# Select numeric only
features = df.select_dtypes(include=['number']).drop(columns=['target_temperature'])
target = df['target_temperature']

# Scale
scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(features)

features_scaled = pd.DataFrame(features_scaled, columns=features.columns)

X_train, X_test, y_train, y_test = train_test_split(
    features_scaled, target, test_size=0.2, random_state=42
)

X_train.to_csv('../content/X_train.csv', index=False)
X_test.to_csv('../content/X_test.csv', index=False)
y_train.to_csv('../content/y_train.csv', index=False)
y_test.to_csv('../content/y_test.csv', index=False)

print("Phase 2 Complete!")
print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

